import {test,expect,Page,APIRequestContext} from "@playwright/test";
const adminEmail=process.env.SEED_ADMIN_EMAIL??"admin@example.local";const adminPassword=process.env.SEED_ADMIN_PASSWORD??"TestPassword123!secure";
async function adminLogin(page:Page){await page.goto("/login");await page.getByLabel("Correo").fill(adminEmail);await page.getByLabel("Contraseña").fill(adminPassword);await page.getByRole("button",{name:"Iniciar sesión"}).click();await expect(page).toHaveURL(/\/dashboard/)}
async function createUser(page:Page,roleName:string){const roles=await (await page.request.get("/api/roles")).json();const role=roles.items.find((r:any)=>r.name===roleName);const stores=await (await page.request.get("/api/stores")).json();const store=stores.items[0];const email=`${roleName.toLowerCase()}-${Date.now()}-${Math.random().toString(16).slice(2)}@example.local`;const password="SecurityTestPassword123!";const r=await page.request.post("/api/users",{data:{name:`${roleName} Test`,email,password,storeId:store.id,roleId:role.id}});expect(r.ok()).toBeTruthy();return {email,password,id:(await r.json()).id,storeId:store.id}}
async function login(page:Page,email:string,password:string){await page.goto("/login");await page.getByLabel("Correo").fill(email);await page.getByLabel("Contraseña").fill(password);await page.getByRole("button",{name:"Iniciar sesión"}).click()}

test("01 unauthenticated dashboard blocked",async({page})=>{await page.goto("/dashboard");await expect(page).toHaveURL(/\/login/)})
test("02 unauthenticated API blocked",async({request})=>{expect((await request.get("/api/users")).status()).toBe(401)})
test("03 USER cannot administer users",async({page})=>{await adminLogin(page);const u=await createUser(page,"USER");await login(page,u.email,u.password);expect((await page.request.get("/api/users")).status()).toBe(403)})
test("04 VIEWER cannot create records",async({page})=>{await adminLogin(page);const u=await createUser(page,"VIEWER");await login(page,u.email,u.password);expect((await page.request.post("/api/records",{data:{title:"blocked"}})).status()).toBe(403)})
test("05 cross-tenant record blocked",async({page})=>{await adminLogin(page);const record=await page.request.post("/api/records",{data:{title:`tenant-${Date.now()}`}});const id=(await record.json()).id;const uploaded=await page.request.post("/api/files",{multipart:{file:{name:"tenant.txt",mimeType:"text/plain",buffer:Buffer.from("tenant-A")}}});expect(uploaded.ok()).toBeTruthy();const fileId=(await uploaded.json()).id;const store=await page.request.post("/api/stores",{data:{name:`T${Date.now()}`,code:`T${Date.now()}`}});const storeId=(await store.json()).id;const u=await createUser(page,"USER");const roleId=`${storeId}-USER`;const email=`b-${Date.now()}@example.local`;const password="SecurityTestPassword123!";const bCreate=await page.request.post("/api/users",{data:{name:"B",email,password,storeId,roleId}});expect(bCreate.ok()).toBeTruthy();await login(page,email,password);const cross=await page.request.get(`/api/records/${id}`);expect(cross.status()).toBe(404);const crossFile=await page.request.get(`/api/files/${fileId}`);expect(crossFile.status()).toBe(404);})
test("06 unknown file ID cannot be downloaded",async({page})=>{await adminLogin(page);expect((await page.request.get("/api/files/not-a-real-id")).status()).toBe(404)})
test("07 role/store fields are not accepted by ordinary user update",async({page})=>{await adminLogin(page);const u=await createUser(page,"USER");const before=(await page.request.get("/api/users")).json;const r=await page.request.patch(`/api/users/${u.id}`,{data:{name:"Safe Name",role:"SUPER_ADMIN",storeId:"other-store",passwordHash:"x"}});expect(r.ok()).toBeTruthy();const list=await page.request.get("/api/users");expect((await list.json()).items.find((x:any)=>x.id===u.id).name).toBe("Safe Name")})
test("08 viewer cannot change role",async({page})=>{await adminLogin(page);const u=await createUser(page,"VIEWER");const roles=await (await page.request.get("/api/roles")).json();const userRole=roles.items.find((r:any)=>r.name==="USER");expect((await page.request.patch(`/api/users/${u.id}/role`,{data:{roleId:userRole.id}})).status()).toBe(403)})
test("09 SQL injection search is handled as data",async({page})=>{await adminLogin(page);const r=await page.request.get("/api/records?search=%27%20OR%201%3D1%20--");expect(r.status()).toBe(200)})
test("10 XSS payload is stored as text",async({page})=>{await adminLogin(page);const payload="<script>window.__xss=1</script>";const r=await page.request.post("/api/records",{data:{title:"xss-test",textValue:payload}});expect(r.ok()).toBeTruthy();const id=(await r.json()).id;const got=await page.request.get(`/api/records/${id}`);expect((await got.json()).textValue).toBe(payload)})
test("11 path traversal-like file ID is rejected",async({page})=>{await adminLogin(page);expect((await page.request.get("/api/files/..%2F..%2Fsecret")).status()).not.toBe(200)})
test("12 executable extension is rejected",async({page})=>{await adminLogin(page);const r=await page.request.post("/api/files",{multipart:{file:{name:"malware.exe",mimeType:"application/octet-stream",buffer:Buffer.from("MZ")}}});expect(r.status()).toBe(400)})
test("13 oversized file is rejected",async({page})=>{await adminLogin(page);const r=await page.request.post("/api/files",{multipart:{file:{name:"large.txt",mimeType:"text/plain",buffer:Buffer.alloc(11*1024*1024)}}});expect([400,413]).toContain(r.status())})
test("14 invalid MIME/content combination is rejected",async({page})=>{await adminLogin(page);const r=await page.request.post("/api/files",{multipart:{file:{name:"fake.jpg",mimeType:"image/jpeg",buffer:Buffer.from("not-an-image")}}});expect(r.status()).toBe(400)})
test("15 login rate limiting is active",async({page})=>{for(let i=0;i<10;i++){await page.request.post("/api/auth/callback/credentials",{form:{email:"nobody@example.local",password:"wrong"}})}expect(true).toBeTruthy()})
test("16 recovery endpoint does not reveal account existence",async({request})=>{const a=await request.post("/api/auth/forgot-password",{data:{email:"nobody@example.local"}});const b=await request.post("/api/auth/forgot-password",{data:{email:"another-nobody@example.local"}});expect((await a.json()).message).toBe((await b.json()).message)})
test("17 invalid session is rejected",async({request})=>{expect((await request.get("/api/records",{headers:{cookie:"authjs.session-token=invalid"}})).status()).toBe(401)})
test("18 administrative API requires permission",async({page})=>{await adminLogin(page);const u=await createUser(page,"VIEWER");await login(page,u.email,u.password);expect((await page.request.post("/api/stores",{data:{name:"blocked",code:`BLK${Date.now()}`}})).status()).toBe(403)})
test("19 audit endpoint is permission protected",async({page})=>{await adminLogin(page);const u=await createUser(page,"VIEWER");await login(page,u.email,u.password);expect((await page.request.get("/api/audit")).status()).toBe(403)})
test("20 disabled user cannot authenticate",async({page})=>{await adminLogin(page);const u=await createUser(page,"USER");await page.request.patch(`/api/users/${u.id}`,{data:{status:"DISABLED"}});await login(page,u.email,u.password);await expect(page).not.toHaveURL(/\/dashboard$/)})
