import {test,expect,Page} from "@playwright/test";
const adminEmail=process.env.SEED_ADMIN_EMAIL??"admin@example.local";
const adminPassword=process.env.SEED_ADMIN_PASSWORD??"TestPassword123!secure";
async function login(page:Page){await page.goto("/login");await page.getByLabel("Correo").fill(adminEmail);await page.getByLabel("Contraseña").fill(adminPassword);await page.getByRole("button",{name:"Iniciar sesión"}).click();await expect(page).toHaveURL(/\/dashboard/)}
test("login and dashboard",async({page})=>{await login(page);await expect(page.getByRole("heading",{name:"Dashboard"})).toBeVisible()});
test("logout",async({page})=>{await login(page);await page.getByRole("button",{name:"Cerrar sesión"}).click();await expect(page).toHaveURL(/\/login/)});
test("create record",async({page})=>{await login(page);await page.goto("/dashboard/records");await page.getByPlaceholder("Título").fill(`E2E ${Date.now()}`);await page.getByRole("button",{name:"Crear registro"}).click();await expect(page.getByRole("table")).toContainText("E2E")});
test("upload and download allowed file",async({page})=>{await login(page);await page.goto("/dashboard/files");await page.locator('input[type="file"]').setInputFiles({name:"e2e.txt",mimeType:"text/plain",buffer:Buffer.from("tenant-safe-file")});await page.getByRole("button",{name:"Subir"}).click();await expect(page.getByRole("table")).toContainText("e2e.txt");const downloadPromise=page.waitForEvent("download");await page.getByRole("link",{name:"Descargar"}).first().click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe("e2e.txt")});
test("protected API rejects anonymous request",async({request})=>{const r=await request.get("/api/records");expect(r.status()).toBe(401)});
test("protected admin route rejects anonymous request",async({page})=>{await page.goto("/dashboard/users");await expect(page).toHaveURL(/\/login/)});
test("tenant isolation blocks cross-store record and file access",async({page})=>{await login(page);const api=page.request;const record=await api.post("/api/records",{data:{title:`Isolation ${Date.now()}`}});expect(record.ok()).toBeTruthy();const recordJson=await record.json();const storeRes=await api.post("/api/stores",{data:{name:`Isolation Store ${Date.now()}`,code:`ISO${Date.now()}`}});expect(storeRes.ok()).toBeTruthy();const store=await storeRes.json();const roles=await (await api.get("/api/roles")).json();const userRole=roles.items.find((r:any)=>r.name==="USER"&&!r.system);expect(userRole).toBeTruthy();const password="TenantTestPassword123!";const created=await api.post("/api/users",{data:{name:"Isolation User",email:`isolation-${Date.now()}@example.local`,password,storeId:store.id,roleId:userRole.id}});expect(created.ok()).toBeTruthy();const email=(await created.json()).email;await page.goto("/login");await page.getByLabel("Correo").fill(email);await page.getByLabel("Contraseña").fill(password);await page.getByRole("button",{name:"Iniciar sesión"}).click();await expect(page).toHaveURL(/\/dashboard/);const crossRecord=await page.request.get(`/api/records/${recordJson.id}`);expect(crossRecord.status()).toBe(404);const crossFile=await page.request.get(`/api/files/nonexistent-cross-tenant-id`);expect(crossFile.status()).toBe(404)});
